"use client";

import Link from "next/link";
import { useState, useTransition } from "react";
import { btnSolid } from "@/components/editorial";
import { generateTailoredDocuments } from "@/lib/tailor-actions";

type Doc = {
  id: string;
  kind: string;
  content: string;
  createdAt: string;
};

export function TailorDocuments({
  applicationId,
  docs,
}: {
  applicationId: string;
  docs: Doc[];
}) {
  const [isPending, startTransition] = useTransition();
  const [error, setError] = useState<string | null>(null);

  const latestResume = docs.find((d) => d.kind === "resume");
  const latestCover = docs.find((d) => d.kind === "cover_letter");
  const hasDocs = latestResume || latestCover;

  function generate() {
    setError(null);
    startTransition(async () => {
      const result = await generateTailoredDocuments(applicationId);
      if (!result.ok) setError(result.error);
    });
  }

  return (
    <div className="space-y-5">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <p className="text-sm text-neutral-400">
          {hasDocs
            ? "Generated by Fable 5 from your base résumé and this posting."
            : "Fable 5 rewrites your base résumé and drafts a cover letter for this posting."}
        </p>
        <button
          type="button"
          onClick={generate}
          disabled={isPending}
          className={btnSolid}
        >
          {isPending
            ? "GENERATING… (~30S)"
            : hasDocs
              ? "REGENERATE"
              : "TAILOR WITH FABLE 5 →"}
        </button>
      </div>

      {error && (
        <p className="border border-neutral-50 p-3 text-sm text-neutral-300">
          {error}
        </p>
      )}

      {latestResume && (
        <DocumentPanel title="TAILORED RÉSUMÉ" doc={latestResume} />
      )}
      {latestCover && <DocumentPanel title="COVER LETTER" doc={latestCover} />}
    </div>
  );
}

function DocumentPanel({ title, doc }: { title: string; doc: Doc }) {
  const [copied, setCopied] = useState(false);

  return (
    <details className="border border-neutral-50" open>
      <summary className="flex cursor-pointer items-center justify-between gap-2 border-b border-neutral-800 bg-neutral-900 px-4 py-2.5">
        <span className="font-mono text-[11px] tracking-[0.18em]">
          {title}
        </span>
        <span className="flex items-center gap-4">
          <button
            type="button"
            onClick={(e) => {
              e.preventDefault();
              navigator.clipboard.writeText(doc.content).then(() => {
                setCopied(true);
                setTimeout(() => setCopied(false), 1500);
              });
            }}
            className="font-mono text-[10px] tracking-[0.14em] text-neutral-500 hover-invert"
          >
            {copied ? "COPIED ✓" : "COPY"}
          </button>
          <Link
            href={`/documents/${doc.id}`}
            target="_blank"
            onClick={(e) => e.stopPropagation()}
            className="font-mono text-[10px] tracking-[0.14em] text-neutral-500 hover-invert"
          >
            PREVIEW ↗
          </Link>
          <a
            href={`/api/documents/${doc.id}/pdf`}
            onClick={(e) => e.stopPropagation()}
            className="font-mono text-[10px] tracking-[0.14em] text-neutral-500 hover-invert"
          >
            PDF ↓
          </a>
        </span>
      </summary>
      <pre className="max-h-96 overflow-y-auto whitespace-pre-wrap bg-neutral-900 px-4 py-3 font-sans text-sm leading-relaxed text-neutral-300">
        {doc.content}
      </pre>
    </details>
  );
}
